### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by avyavkumar** [avyavkumar/HH-MPI#4]
Harsha,

Can you get back to me on the following?

How you formed the ring lattice in -
line 205, https://github.com/avyavkumar/HH-MPI/blob/master/small-world-network-HH-model.c. 
Correct me if I am wrong, but the basic structure of the network is four connections into the neuron; and four out of it. Just elaborate on the reason behind sum(i,j) > N and sum(i,j) < 0, please. 

Regards,

Avyav

**Comment by harshakoneru** [comment]
Hi, 

N is the number of neurons in the network.
k is the average number of connections per neuron.
The graph is un-directional => f(i,j) = f(j,i) where i,j are nodes and f is any relationship between them.
The way you create a small world network is to start with a ring lattice with k/2 connections on either side of the neuron, and randomly rewire the connections with a particular probability p.

In the code, k = 8
So I have 4 connections to the left of the neuron in the ring lattice and 4 to the right.
And that's what that part of the code does.

You can use this for reference: http://www.nature.com/nature/journal/v393/n6684/abs/393440a0.html
